- name: install tmux
  package: 
    name: "{{item}}"
    state: present
  loop:
    - tmux
    - xclip
  become: true

- name: add a tmux custom conf
  ansible.builtin.template:
    src: .tmux.conf.j2
    dest: ~/.tmux.conf
